version: '2'

services:

  postgres:
    image: kiasaki/alpine-postgres
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=51316918519
      - POSTGRES_USER=sonar
      - POSTGRES_DB=sonar

  sonar:
    image: sonarqube:alpine
    ports:
      - 9000:9000
      - 9092:9092
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=51316918519
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    links:
      - postgres
