version: "2"

services:

  jenkins:
    image: jenkins
    ports:
      - 49001:8080

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://database:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf 
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - sonarqube_projects:/projects
    links:
      - database

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:

  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  sonarqube_projects:
  postgresql:
  postgresql_data:

